apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: <YOUR EMAIL ADDRESS>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: le-key-ref
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        cloudflare:
          email: <YOUR EMAIL ADDRESS>
          apiKeySecretRef:
            name: cloudflare-apikey-secret
            key: key
      selector:
        dnsZones:
        - 'suse.ninja'
